# Generated by Django 4.2.30 on 2026-08-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('tab_switch_count', models.IntegerField(default=0)),
                ('focus_score', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
