# Generated by Django 4.2.30 on 2026-08-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('temporary_session_duration', models.IntegerField(default=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_screen_time_limit', models.IntegerField(default=120)),
                ('session_limit', models.IntegerField(default=45)),
                ('eye_break_interval', models.IntegerField(default=20)),
                ('whitelisted_websites', models.JSONField(default=list)),
                ('blacklisted_websites', models.JSONField(default=list)),
                ('blocked_apps', models.JSONField(default=list)),
            ],
        ),
    ]
