# Generated by Django 6.0.8 on 2026-08-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restriction',
            name='content_filter_intensity',
            field=models.CharField(default='Standard', max_length=20),
        ),
        migrations.AddField(
            model_name='restriction',
            name='morse_pattern',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
