export const COPY = {
  brand: {
    name: "FocusPath",
    tagline: "Plans that rebuild themselves.",
    modeAdult: "Adult Mode",
    modeKids: "Kid's Mode",
  },
  nav: {
    dashboard: "Dashboard",
    schedule: "Schedule",
    planner: "Planner",
    reports: "Reports",
    insights: "Insights",
    community: "Community",
    greeting: "Good Morning, Alex",
  },
  splash: {
    title: "FocusPath",
    tagline: "Plans that rebuild themselves.",
  },
  modeSelect: {
    title: "Select Your Mode",
    adultTitle: "Adult Mode",
    adultDesc: "Plan, track focus, and study smarter.",
    kidsTitle: "Kid's Mode",
    kidsDesc: "Fun, guided study time.",
    pinNotice: "Parents can enable Kid's Mode with a PIN",
    alreadyAccount: "Already have an account? Log In",
  },
  login: {
    heading: "Welcome back",
    subheading: "Manage your cognitive focus journey",
    emailLabel: "Email address",
    passwordLabel: "Password",
    forgotPassword: "Forgot?",
    rememberMe: "Remember this device",
    loginBtn: "Log In →",
    orContinue: "Or continue with",
    sso: "SSO",
    biometric: "Biometric",
    noAccount: "Don't have an account? Create account",
    footer: {
      privacy: "Privacy Policy",
      terms: "Terms of Service",
      help: "Help Center",
      copyright: "© 2024 FocusPath Inc.",
    },
  },
  onboarding: {
    heading: "Let's build your study plan",
    subheading: "Organize your academic goals and we'll handle the timing.",
    uploadTitle: "Upload your syllabus",
    uploadSubtitle: "PDF or high-quality image of your course outline",
    browseFiles: "Browse Files",
    addManually: "ADD SUBJECTS MANUALLY",
    subjectPlaceholder: "Subject Name (e.g. Psychology 101)",
    priorityPlaceholder: "Priority",
    addBtn: "+ Add",
    plannedTitle: "Planned Subjects",
    hoursTitle: "Hours you can study per day",
    hoursSubtitle: "Adjust to your typical availability",
    generateBtn: "Generate My Timetable",
    aiNote: "Our AI will create a balanced schedule based on your deadlines.",
  },
  dashboardMorning: {
    heading: "Daily Overview",
    subheading: "Your productivity is peaking today. Stay on track with these insights.",
    focusScoreTitle: "FOCUS SCORE",
    focusScoreStatus: "Optimal",
    focusScoreNote: "Above 92% of your weekly average performance.",
    aiTitle: "AI Suggestion",
    aiBody: "You're most productive at 10 AM — shift Advanced Mathematics here for better retention?",
    aiBtn: "Optimize Path ↗",
    timetableTitle: "Today's Timetable",
    timetableLink: "View All",
    trendTitle: "Weekly Concentration Trend",
    trendSubtitle: "Your peak focus hours over the last 7 days.",
    statStudyHours: "Total Study Hours",
    statDeepSessions: "Deep Sessions",
    proTipBadge: "Pro Tip",
    proTipTitle: "Optimize your environment for cognitive comfort.",
    proTipBody: "Recent data shows your focus is 15% higher when you work in naturally lit environments. Consider taking your \"Deep Work: History\" session near a window today.",
    proTipBtn: "Explore Ergonomic Guides",
  },
  dashboardEvening: {
    heading: "How did today go?",
    subheading: "Take a moment to reflect on your progress and calibrate for tomorrow.",
    streakBadge: "🏆 4 Day Streak!",
    goalTitle: "WEEKLY GOAL COMPLETION",
    tasksTitle: "Daily Tasks",
    addTaskBtn: "+ Add a task you did that wasn't planned",
    wellDoneTitle: "Well Done!",
    wellDoneBody: "You hit your primary focus targets today. Consistency is your superpower.",
    reflectionTitle: "Daily Reflection",
    reflectionPlaceholder: "What was your biggest win or obstacle today?",
    saveBtn: "Save & Update Plan →",
    proTipTitle: "Pro Tip",
    proTipBody: "Most of your tasks were completed in the morning. Shift heavy focus sessions before 1 PM.",
  },
  schedule: {
    heading: "Weekly Timetable",
    subheading: "Manage your cognitive load and structure your learning path.",
    cognitiveLoadTitle: "Weekly Cognitive Load",
    cognitiveLoadSubtitle: "You've reached 64% of your study targets for this week. Keep up the momentum!",
  },
  session: {
    badge: "• FOCUS TRACKING ACTIVE",
    label: "CURRENT SESSION",
    title: "Advanced Mathematics II – Linear Algebra",
    completeBtn: "✓ Mark Complete",
    pauseBtn: "⏸ Pause Session",
    resumeBtn: "▶ Resume Session",
    brainStateTitle: "BRAIN STATE",
    brainStateValue: "Deep Work Stage 2",
    exit: "Exit Session",
  },
  rebuild: {
    heading: "Let's adjust your plan",
    subheading: "You missed 2 tasks — here's an updated plan that still meets all your exam deadlines.",
    banner: "All exam deadlines still on track",
    originalTitle: "Original Plan",
    rebuiltTitle: "Rebuilt Plan",
    safetyTitle: "Safety Margin Maintained",
    safetyDesc: "Plan accommodates all 4 upcoming exam milestones.",
    acceptBtn: "Accept new plan",
    adjustBtn: "Adjust manually",
    tipBadge: "Tip",
    tipBody: "Your peak focus hours are between 2 PM and 5 PM. We've moved your hardest tasks there.",
  },
  insights: {
    eyebrow: "ADULT MODE • ANALYTICS",
    heading: "Performance Deep-Dive",
    timeframe: "Timeframe: Last 30 Days",
    totalDeepWork: "Total Deep Work",
    avgFocus: "Avg. Daily Focus",
    streakTitle: "14 Day Streak",
    streakBody: "You're in the top 5% of learners this week. Keep the momentum going!",
    trendTitle: "Focus Score Trend",
    trendSubtitle: "Measured peak cognitive state performance",
    subjectCompletionTitle: "Subject-wise Completion",
    aiSuggestionTitle: "Focus AI Suggestion",
    aiSuggestionBody: "Based on your trend, morning sessions yield 15% more productivity.",
    scheduleMorningBtn: "Schedule Morning Focus",
    nextUpTitle: "NEXT UP",
    nextUpTopic: "Neural Networks Part 2",
    startsIn: "Starts in 15m",
  },
};
