# Generated by Django 6.0.8 on 2026-08-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parent_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
