# Generated by Django 6.0.8 on 2026-08-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age_group',
            field=models.CharField(blank=True, choices=[('1-3', '1-3 years'), ('4-6', '4-6 years'), ('7-8', '7-8 years'), ('9-10', '9-10 years'), ('11-12', '11-12 years')], max_length=10, null=True),
        ),
    ]
