# Generated by Django 6.0.8 on 2026-08-25 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_parent_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_study_start', models.TimeField(blank=True, null=True)),
                ('morning_study_end', models.TimeField(blank=True, null=True)),
                ('work_college_start', models.TimeField(blank=True, null=True)),
                ('work_college_end', models.TimeField(blank=True, null=True)),
                ('evening_study_start', models.TimeField(blank=True, null=True)),
                ('evening_study_end', models.TimeField(blank=True, null=True)),
                ('snack_time_start', models.TimeField(blank=True, null=True)),
                ('snack_time_end', models.TimeField(blank=True, null=True)),
                ('dinner_time_start', models.TimeField(blank=True, null=True)),
                ('dinner_time_end', models.TimeField(blank=True, null=True)),
                ('default_daily_hours', models.PositiveIntegerField(default=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='routine', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
