# Generated by Django 6.0.8 on 2026-08-27 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_age_group'),
        ('users', '0003_userroutine'),
    ]

    operations = [
    ]
