# Generated by Django 6.0.8 on 2026-08-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_0002_user_age_group_0003_userroutine'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('Kindergarten', 'Kindergarten'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6')], max_length=20, null=True),
        ),
    ]
