# Generated by Django 6.0.8 on 2026-08-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kid_pin_plain',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
