# Generated by Django 6.0.8 on 2026-08-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_kid_pin_plain'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age_range',
            field=models.CharField(blank=True, choices=[('4-5 Years', '4-5 Years'), ('6-7 Years', '6-7 Years'), ('8-9 Years', '8-9 Years'), ('10-11 Years', '10-11 Years'), ('12+ Years', '12+ Years')], max_length=20, null=True),
        ),
    ]
