# Generated by Django 6.0.8 on 2026-08-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_age_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age_range',
        ),
        migrations.AddField(
            model_name='user',
            name='security_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='security_hint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
