# Generated by Django 4.2.30 on 2026-08-04 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='starreward',
            name='child',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='star_wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='childbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards.badge'),
        ),
        migrations.AddField(
            model_name='childbadge',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='childbadge',
            unique_together={('child', 'badge')},
        ),
    ]
