# Generated by Django 6.0.8 on 2026-08-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_subject_module_topic_studysession_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='difficulty',
            field=models.CharField(default='Medium', max_length=10),
        ),
    ]
