# Generated by Django 6.0.8 on 2026-08-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_subject_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='daily_subject_hours',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='subject',
            name='plan_type',
            field=models.CharField(default='Study', max_length=20),
        ),
    ]
